--SELECT FIRST_NAME LAST_NAME FROM EMPLOYEES WHERE EMAIL LIKE 'C%';
--SELECT * FROM EMPLOYEES WHERE SALARY > 2000 OR EMAIL LIKE 'C%'
SELECT SALARIO FROM JUGADORES WHERE JUGADORES.EQUIPO_ID IN
(SELECT EQUIPO_ID FROM EQUIPO WHERE NOMBRE = 'REAL MADRID');