--------------------------------------------------------
-- Archivo creado  - miércoles-diciembre-07-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ULTRAS
--------------------------------------------------------

  CREATE TABLE "NEW"."ULTRAS" 
   (	"NOMBRE" VARCHAR2(20 BYTE), 
	"DNI" NUMBER, 
	"FECHA_NACIMIENTO" DATE, 
	"AFICION_ID" NUMBER, 
	"ULTRA_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ULTRAS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "NEW"."ULTRAS_PK" ON "NEW"."ULTRAS" ("ULTRA_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table ULTRAS
--------------------------------------------------------

  ALTER TABLE "NEW"."ULTRAS" ADD CONSTRAINT "ULTRAS_PK" PRIMARY KEY ("ULTRA_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "NEW"."ULTRAS" MODIFY ("ULTRA_ID" NOT NULL ENABLE);
  ALTER TABLE "NEW"."ULTRAS" MODIFY ("AFICION_ID" NOT NULL ENABLE);
  ALTER TABLE "NEW"."ULTRAS" MODIFY ("NOMBRE" NOT NULL ENABLE);
